"""
exponent.py
-----------
Additive coordinate chart on the cyclic group Z/2^(k-2).

Every odd unit modulo 2^k can be written as 5^e with e ∈ Z/N where
N = 2^(k-2).  This module provides the exponential map e ↦ 5^e
together with the finite-difference calculus on the exponent domain.
"""
from __future__ import annotations

from collections.abc import Callable


class ExponentSpace:
    """
    Model the multiplicative group generated by g as an additive space.

    The group ⟨g⟩ = {g^e : e = 0, 1, …, N-1} where N = 2^(k-2) is
    isomorphic to Z/N.  This class provides the exponential map
    (lift) together with a noncommutative difference calculus.

    Parameters
    ----------
    g : int
        Generator; must satisfy g ≡ 5 (mod 8) for maximal order.
    k : int
        Bit-width of the ambient ring Z/2^k (k ≥ 3).
    """

    def __init__(self, g: int, k: int) -> None:
        if k < 3:
            raise ValueError("k must be ≥ 3")
        if g & 7 != 5:
            raise ValueError("Generator g must satisfy g ≡ 5 (mod 8)")
        self.g = g
        self.k = k
        self.N = 1 << (k - 2)

    def lift(self, e: int) -> int:
        """
        Compute g^e mod 2^k for e ∈ Z/N.

        The map e ↦ g^e is an exponential (additive → multiplicative).
        """
        return pow(self.g, e, 1 << self.k)

    def difference(self, f: Callable[[int], int], e: int) -> int:
        """
        Forward finite difference (Df)(e) = f(e+1) - f(e).

        For the function f(e) = g^e this satisfies the eigenfunction
        identity D(g^e) = (g-1)·g^e.
        """
        return (f(e + 1) - f(e)) & self._mask()

    def integrate(self, f: Callable[[int], int], max_k: int = 14) -> int:
        """
        Discrete integral of f over Z/N.

        Returns Σ_{e=0}^{N-1} f(e)  (mod 2^k).

        Raises ValueError if k > max_k because N = 2^{k-2} grows
        exponentially and iterating over all seeds is impractical.
        """
        if self.k > max_k:
            raise ValueError(
                f"integrate with k={self.k} requires 2^{self.k-2} iterations; "
                f"limit to k ≤ {max_k} or use a closed form"
            )
        total = 0
        for e in range(self.N):
            total += f(e)
        return total & self._mask()

    def is_eigenfunction(self, f: Callable[[int], int], e: int) -> bool:
        """
        Check whether the eigenfunction identity D(g^e) = (g-1)·g^e
        holds at exponent e.

        This identity is the foundation of the noncommutative
        difference calculus on the exponent domain.
        """
        lhs = self.difference(f, e)
        rhs = ((self.g - 1) * f(e)) & self._mask()
        return lhs == rhs

    def _mask(self) -> int:
        return (1 << self.k) - 1
