from dyadic_math._version import __version__

# 2a. Dynamics
from dyadic_math.basin import BasinExplorer, GhostHunt, LayerGhostDiagnosticV2, precision_sweep

# 2d. Extensions
from dyadic_math.crt import CRTDualNumber, CRTDualProcessor, combined_stability
from dyadic_math.fourier import (
    analytic_coefficients,
    analytic_step_count,
    dft,
    dyadic_coefficients,
    fourier_summary,
    power_spectrum,
    step_count_fn,
    ultrametric_uncertainty,
)
from dyadic_math.isometry import (
    exponent_valuation_profile,
    isometry_pair_test,
    isometry_summary,
    trace_alpha_independence,
    trace_exponent_independence,
    verify_isometry,
)
from dyadic_math.iwasawa import (
    MatrixCoordinates,
    congruence_depth,
    filtration_portrait,
    filtration_residue,
    holonomy_depth_profile,
    ldu_decompose,
    matrix_commutator,
    matrix_coordinates,
    verify_commutator_depth,
)
from dyadic_math.mersenne import (
    bootstrap_cost,
    cliff_constant,
    cliff_constant_unified,
    cliff_formula,
    compare_bootstrap_strategies,
    dlog_with_lut,
    exp2_neg4,
    mersenne_cliff_conjecture,
    mersenne_cliff_table,
    mersenne_coordinates,
    optimal_bootstrap,
    verify_c_formula,
    verify_cliff_constant,
    verify_connection,
    verify_core_identity,
    verify_lut_dlog,
    verify_unified_formula,
)
from dyadic_math.nonabelian import NonAbelianCRTDual, phase_alignment_experiment

# 2b. General p-adic
from dyadic_math.padic_roots import (
    compare_methods,
    convergence_profile,
    halley_step,
    lift_root,
    newton2_step,
    newton3_step,
    newton_correction_uniformity,
    newton_step,
    verify_order,
)
from dyadic_math.separation import (
    newton_trajectory,
    predicted_separation,
    separation_step,
    step_count_profile,
    ultrametric_ball_tree,
    verify_separation,
)

# 2c. Weight stability analysis
from dyadic_math.weight_stability import WeightStabilityDiagnostics

__all__ = [
    "__version__",
    "analytic_coefficients",
    "analytic_step_count",
    "BasinExplorer",
    "bootstrap_cost",
    "cliff_constant",
    "cliff_constant_unified",
    "cliff_formula",
    "combined_stability",
    "compare_bootstrap_strategies",
    "compare_methods",
    "congruence_depth",
    "convergence_profile",
    "CRTDualNumber",
    "CRTDualProcessor",
    "dft",
    "dlog_with_lut",
    "dyadic_coefficients",
    "exponent_valuation_profile",
    "exp2_neg4",
    "filtration_portrait",
    "filtration_residue",
    "fourier_summary",
    "GhostHunt",
    "halley_step",
    "holonomy_depth_profile",
    "isometry_pair_test",
    "isometry_summary",
    "LayerGhostDiagnosticV2",
    "ldu_decompose",
    "lift_root",
    "MatrixCoordinates",
    "matrix_coordinates",
    "matrix_commutator",
    "mersenne_cliff_table",
    "mersenne_cliff_conjecture",
    "mersenne_coordinates",
    "newton2_step",
    "newton3_step",
    "newton_correction_uniformity",
    "newton_step",
    "newton_trajectory",
    "NonAbelianCRTDual",
    "optimal_bootstrap",
    "phase_alignment_experiment",
    "power_spectrum",
    "precision_sweep",
    "predicted_separation",
    "separation_step",
    "step_count_fn",
    "step_count_profile",
    "trace_alpha_independence",
    "trace_exponent_independence",
    "ultrametric_ball_tree",
    "ultrametric_uncertainty",
    "verify_c_formula",
    "verify_cliff_constant",
    "verify_commutator_depth",
    "verify_connection",
    "verify_core_identity",
    "verify_isometry",
    "verify_lut_dlog",
    "verify_order",
    "verify_separation",
    "verify_unified_formula",
    "WeightStabilityDiagnostics",
]
